# Generated by Django 3.0.8 on 2020-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200731_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id',
            new_name='idd',
        ),
    ]
